import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jonathan Voss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://www.github.com/asteroidsgithub">
            asteroidsgithub.github.io
          </a>
        </h1>

        <p className={styles.description}>
          I'm busy working on my profile, but in the mean time check out my
          other platforms.{" "}
        </p>

        <div className={styles.grid}>
          <a
            href="https://www.github.com/asteroidsgithub"
            className={styles.card}
          >
            <h2>Github.com &rarr;</h2>
            <p>All my open-source code and cool projects i'm working on.</p>
          </a>

          <a href="https://twitter.com/AsteroidsLive" className={styles.card}>
            <h2>Twitter &rarr;</h2>
            <p>
              Bad takes on EVERYTHING. Mainly New Zealand politics and apple
              devices.
            </p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
